export const LEETCODE_WEBSITE_URL = "https://leetcode.com";
export const LEETCODE_API_ENDPOINT =
  "https://cors-anywhere.herokuapp.com/https://leetcode.com/graphql";
// export const LEETCODE_API_TOPICS_ENDPOINT =
//   "https://cors-anywhere.herokuapp.com/https://leetcode.com/_next/data/lYmU2J-PXaqwL3Mv1FM8J/problemset/all.json?slug=all";

export const LEETCODE_TOPICS = [
  "Array",
  "String",
  "Hash Table",
  "Math",
  "Dynamic Programming",
  "Sorting",
  "Greedy",
  "Depth-First Search",
  "Database",
  "Binary Search",
  "Breadth-First Search",
  "Tree",
  "Matrix",
  "Two Pointers",
  "Binary Tree",
  "Bit Manipulation",
  "Heap (Priority Queue)",
  "Stach",
  "Graph",
  "Prefix Sum",
  "Design",
  "Simulation",
  "Counting",
  "Backtracking",
  "Sliding Window",
  "Union Find",
  "Linked List",
  "Ordered Set",
  "Monotonic Stack",
  "Enumeration",
  "Recursion",
  "Trie",
  "Divide and Conquer",
  "Binary Search Tree",
  "Bitmask",
  "Queue",
  "Number Theory",
  "Segment Tree",
  "Memoization",
  "Geometry",
  "Topological Sort",
  "Binary Indexed Tree",
  "Hash Function",
  "Game Theory",
  "Shortest Path",
  "Combinatorics",
  "Data Stream",
  "Interactive",
  "String Matching",
  "Rolling Hash",
  "Brainteaser",
  "Randomized",
  "Monotonic Queue",
  "Merge Sort",
  "Iterator",
  "Concurrency",
  "Doubly-Linked List",
  "Probability and Statistics",
  "Quickselect",
  "Bucket Sort",
  "Suffix Array",
  "Minimum Spanning Tree",
  "Counting Sort",
  "Shell",
  "Line Sweep",
  "Reservoir Sampling",
  "Eulerian Circuit",
  "Radix Sort",
  "Strongly Connected Component",
  "Rejection Sampling",
  "Biconnected Component",
];
